# Generated by Django 4.2 on 2023-05-02 04:50

from django.db import migrations, models
import main.services


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=main.services.upload_sertificate_path)),
                ('image', models.ImageField(upload_to=main.services.upload_sertificate_path)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
