# Generated by Django 4.2 on 2023-05-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificate',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
