# Generated by Django 4.2 on 2023-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sertificate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
