# Generated by Django 4.2 on 2023-05-02 05:54

from django.db import migrations, models
import main.services


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sertificate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to=main.services.upload_coding_lang_path)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
