# Generated by Django 4.2 on 2023-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_codinglanguage_alter_sertificate_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codinglanguage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sertificate',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contact',
            name='tel1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
