# Generated by Django 4.2 on 2023-05-02 15:07

from django.db import migrations, models
import main.services


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_codinglanguage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.PositiveSmallIntegerField(default=1)),
                ('clients', models.PositiveSmallIntegerField(default=1)),
                ('work_hour', models.PositiveSmallIntegerField(default=0)),
                ('posts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=300)),
                ('from_where', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=main.services.upload_quote_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
