# Generated by Django 4.2 on 2023-05-02 15:12

from django.db import migrations, models
import main.services


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_funfact_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='funfact',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.services.upload_cv_path),
        ),
    ]
