# Generated by Django 4.2 on 2023-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_funfact_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='funfact',
            name='about_me',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
